### ISSUE TITLE
Dependencies are not loading in runtime.

### ISSUE THREAD

**Issue by darkestpriest** [darkestpriest/money-exchange-rater#1]
When the artifact is compiled using gradle its dependencies are not fully loaded in rutime, for example, the reflections library is not getting loaded in runtime when an example app is tested.

Possible fixes:
* Create a fat-jar artifact and deploy it to the main repository.
* Research a way to include this dependencies in the pom used in the repository.

**Comment by darkestpriest** [comment]
When a test app is running I got this exception:
`Caused by: java.lang.ClassNotFoundException: org.reflections.Reflections
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 3 more`

The dependencies are not included in runtime.

**Comment by darkestpriest** [comment]
Fixed on commit: https://github.com/darkestpriest/money-exchange-rater/commit/c7ca42f4151868aa4719833b1f553793b9314d72
